<?php

namespace App\Domain\Resources\Services;

class ResourceCatalogService
{
    public static function getData(): array
    {
        return [
            'checklists' => [
                [
                    'id' => 'mf',
                    'ic' => 'i-growth',
                    't' => 'Start a mutual fund SIP',
                    'd' => 'Everything needed to complete KYC and register a mandate in one visit.',
                    'items' => [
                        'PAN card — original and a copy',
                        'Aadhaar card — original and a copy',
                        'One passport-size photograph',
                        'Cancelled cheque, or a bank statement showing name, account number and IFSC',
                        'Mobile number and email linked to your Aadhaar',
                        'Nominee: full name, relationship, date of birth',
                        'Bank account for the auto-debit mandate',
                        'Your goal, the amount and the date you need it',
                    ],
                ],
                [
                    'id' => 'health',
                    'ic' => 'i-heart',
                    't' => 'Buy or port health cover',
                    'd' => 'What the insurer will ask for, and what you must disclose.',
                    'items' => [
                        'PAN and Aadhaar for every member to be covered',
                        'Date of birth proof for each member',
                        'Full medical history — diagnosed conditions, surgeries, hospitalisations',
                        'Current prescriptions and dosages',
                        'Recent test reports, if any exist',
                        'Height and weight for each member',
                        'Existing policy copy and renewal date, if porting',
                        'Claim history on the current policy',
                    ],
                ],
                [
                    'id' => 'motor',
                    'ic' => 'i-car',
                    't' => 'Renew motor insurance',
                    'd' => 'Keep these at hand and renewal takes minutes rather than days.',
                    'items' => [
                        'Registration Certificate (RC)',
                        'Previous policy copy with the expiry date',
                        'Driving licence',
                        'Current odometer reading',
                        'Claim history for the expiring year',
                        'Details of any accessories fitted',
                        'Hypothecation details, if the vehicle is financed',
                        'Vehicle available for inspection if the policy has already lapsed',
                    ],
                ],
                [
                    'id' => 'home',
                    'ic' => 'i-home',
                    't' => 'Home loan file',
                    'd' => 'A complete file is the difference between a sanction and a series of queries.',
                    'items' => [
                        'KYC and photographs for every applicant and co-applicant',
                        'Last 3 salary slips and Form 16 — salaried',
                        'ITR with computation and financials for 2–3 years — self-employed',
                        '6–12 months bank statements for all accounts',
                        'Agreement to sell, allotment letter or complete property chain',
                        'Approved building plan and cost estimate, for construction',
                        'Sanction letters and statements for every existing loan',
                        'Own-contribution funds, with a traceable source',
                    ],
                ],
                [
                    'id' => 'msme',
                    'ic' => 'i-brief',
                    't' => 'MSME / CGTMSE loan file',
                    'd' => 'Prepared to the standard a credit officer expects to receive.',
                    'items' => [
                        'Udyam registration certificate',
                        'KYC of proprietor, partners or directors',
                        'GST registration and the last 12 months of returns',
                        'ITR with computation and financials for 2–3 years',
                        '12 months bank statements for every current account',
                        'Project report: cost, means of finance and projections',
                        'Machinery quotations or proforma invoices',
                        'Existing sanction letters and repayment track record',
                        'Partnership deed, or MOA and AOA',
                    ],
                ],
                [
                    'id' => 'stress',
                    'ic' => 'i-scale',
                    't' => 'Stressed account meeting',
                    'd' => 'Bring these and the first meeting becomes productive rather than exploratory.',
                    'items' => [
                        'Every notice and letter received, with the envelopes and dates',
                        'Sanction letters and loan agreements',
                        'Account statements covering the default period',
                        'Latest financials and a realistic cash-flow position',
                        'Details of security offered and of any guarantors',
                        'Any settlement offer already made or received, in writing',
                        'Your current credit bureau report',
                        'A written note of what you can genuinely afford to pay',
                    ],
                ],
            ],
            'faqCategories' => [
                ['id' => 'gen', 'label' => 'Getting started'],
                ['id' => 'inv', 'label' => 'Investments'],
                ['id' => 'ins', 'label' => 'Insurance'],
                ['id' => 'loan', 'label' => 'Loans'],
                ['id' => 'adv', 'label' => 'Advisory'],
                ['id' => 'priv', 'label' => 'Privacy & trust'],
            ],
            'faqs' => [
                ['c' => 'gen', 'q' => 'What does the first meeting cost?', 'a' => 'Nothing. The first conversation runs about thirty minutes, covers your situation rather than any product, and ends with a written summary. There is no obligation to buy anything afterwards.'],
                ['c' => 'gen', 'q' => 'How is KB Finvest paid, then?', 'a' => 'On mutual funds, the AMC pays a distribution commission out of the scheme, disclosed in your account statement. On insurance, the insurer pays standard commission built into premium. On loans, fees are charged by lenders. We charge no separate advisory fee.'],
                ['c' => 'gen', 'q' => 'Do I have to come to the office?', 'a' => 'No. Most clients in Ludhiana prefer to, and you are welcome any working day. For everyone else we run the same process by video call, phone and WhatsApp.'],
                ['c' => 'gen', 'q' => 'Which languages can we talk in?', 'a' => 'English, Hindi or Punjabi — whichever you are most comfortable in.'],
                ['c' => 'inv', 'q' => 'What is the smallest SIP I can start?', 'a' => 'Many schemes accept ₹500 a month. Starting small and increasing every year is far more effective than waiting until you can commit a large amount.'],
                ['c' => 'inv', 'q' => 'Will you tell me which fund gives the best return?', 'a' => 'No, and you should be cautious with anyone who does. Past performance does not predict future results. We explain the mandate, cost, risk, and category fit.'],
                ['c' => 'inv', 'q' => 'Is my money held by KB Finvest?', 'a' => 'Never. Payments go directly to AMC, insurer, or lender. Securities sit in your own demat account.'],
                ['c' => 'ins', 'q' => 'How much health cover does a family in Ludhiana need?', 'a' => 'A realistic two-day ICU admission locally is a good benchmark. A smaller base policy plus a super top-up usually yields far larger cover for the same money.'],
                ['c' => 'ins', 'q' => 'Do you help when I actually have to claim?', 'a' => 'Yes, and that is most of the job. Cashless pre-authorisation, document assembly for reimbursement, and follow-up with the hospital desk.'],
                ['c' => 'loan', 'q' => 'Does KB Finvest lend money?', 'a' => 'No. We are a facilitator. Sanctions and terms are decided entirely by regulated lenders. We never collect loan repayments.'],
                ['c' => 'loan', 'q' => 'Can I really get a business loan with no collateral?', 'a' => 'For micro and small enterprises, often yes via CGTMSE guarantee cover up to ₹10 crore, and RBI rules bar banks from demanding collateral for MSE loans up to ₹20 lakh.'],
                ['c' => 'adv', 'q' => 'Are pre-IPO shares safe?', 'a' => 'No. They are illiquid, unlisted, and carry high risk. Treat them only as a small satellite allocation you can afford to lose.'],
                ['c' => 'priv', 'q' => 'What happens to details submitted on this site?', 'a' => 'They are used solely to answer your enquiry. We never sell, rent, or spam your data, and we comply with the DPDP framework.'],
            ],
            'glossary' => [
                ['t' => 'SIP', 'd' => 'Systematic Investment Plan — a fixed amount invested in a mutual fund scheme at a fixed interval, usually monthly.'],
                ['t' => 'NAV', 'd' => 'Net Asset Value — the per-unit value of a mutual fund scheme, published at the end of each business day.'],
                ['t' => 'XIRR', 'd' => 'The annualised return on a series of cash flows that arrive at irregular dates. The right measure for a SIP.'],
                ['t' => 'CAGR', 'd' => 'Compound Annual Growth Rate — the smoothed annual return on a single lump sum over a period.'],
                ['t' => 'Exit load', 'd' => 'A charge deducted if you redeem mutual fund units before a stated period. Scheme specific.'],
                ['t' => 'SWP', 'd' => 'Systematic Withdrawal Plan — a fixed amount taken out of a scheme at a fixed interval.'],
                ['t' => 'PMS', 'd' => 'Portfolio Management Service — a managed mandate with a SEBI-registered portfolio manager, minimum ₹50 lakh.'],
                ['t' => 'HLV', 'd' => 'Human Life Value — the economic value of your future income, used to size life cover.'],
                ['t' => 'IDV', 'd' => 'Insured Declared Value — the maximum a motor policy pays on total loss. Listed price less depreciation.'],
                ['t' => 'NCB', 'd' => 'No Claim Bonus — a renewal discount earned for each claim-free year. It belongs to you, not the vehicle.'],
                ['t' => 'EMI', 'd' => 'Equated Monthly Instalment — equal monthly repayment covering both interest and principal.'],
                ['t' => 'FOIR', 'd' => 'Fixed Obligation to Income Ratio — the share of your income already committed to EMIs. Lenders cap it.'],
                ['t' => 'CGTMSE', 'd' => 'Credit Guarantee Fund Trust for Micro and Small Enterprises — guarantees collateral-free MSE credit.'],
                ['t' => 'Udyam', 'd' => 'The free government registration that identifies an enterprise as an MSME.'],
            ],
            'areas' => [
                'ludhiana' => ['Central Town', 'Model Town', 'Sarabha Nagar', 'Civil Lines', 'BRS Nagar', 'Dugri', 'Pakhowal Road', 'Ferozepur Road', 'Gill Road', 'Jamalpur', 'Shimlapuri', 'Haibowal', 'Kitchlu Nagar', 'Rajguru Nagar', 'Sahnewal', 'Khanna', 'Doraha', 'Samrala', 'Machhiwara', 'Jagraon', 'Raikot', 'Mullanpur Dakha'],
                'punjab' => ['Jalandhar', 'Moga', 'Barnala', 'Sangrur', 'Patiala', 'Nawanshahr', 'Rupnagar', 'Fatehgarh Sahib', 'Bathinda', 'Ferozepur', 'Amritsar', 'Chandigarh & Mohali'],
            ],
        ];
    }
}
