<?php

namespace App\Domain\Loans\Services;

class LoanCatalogService
{
    public static function getData(): array
    {
        $loanLine = 'KB Finvest facilitates introductions to regulated lenders. Sanction, interest rate, charges and final terms are decided solely by the lender. We do not collect loan repayments or hold loan funds.';

        return [
            'services' => [
                [
                    'id' => 'lap',
                    'ic' => 'i-bank',
                    'title' => 'Loan Against Property',
                    'tag' => 'Residential · Commercial · Industrial',
                    'lead' => 'Release value from property you already own, at a rate far below unsecured borrowing, over a long tenure. The trade-off is real: the property secures the loan.',
                    'who' => [
                        'Business owners funding expansion or consolidating costlier debt',
                        'Families funding education, a wedding or a medical event',
                        'Self-employed professionals with strong assets and lumpy income',
                    ],
                    'what' => [
                        'Eligible property: Self-occupied or rented residential, commercial or industrial premises with a clear, marketable title.',
                        'How much: Lenders advance a percentage of the valuer’s assessment, not of the price you paid or the circle rate. Expect a meaningful haircut.',
                        'Income assessment: Salaried on net salary and FOIR; self-employed on ITRs, audited financials and banking. Some lenders assess on banking turnover alone.',
                        'Title and legal: Chain of title, approved plan, occupancy certificate, encumbrance search and the lender’s own legal opinion.',
                        'Balance transfer and top-up: Moving an existing LAP to a lower rate and drawing additional funds in the same transaction.',
                    ],
                    'docs' => [
                        'KYC — PAN, Aadhaar, photographs',
                        'Income proof — 2–3 years ITR with computation, or salary slips and Form 16',
                        '6–12 months bank statements of all operating accounts',
                        'Complete property chain documents and approved plan',
                        'Existing loan statements and sanction letters',
                        'Business proof — GST returns, registration certificates',
                    ],
                    'steps' => [
                        'Eligibility worked out before any application is filed',
                        'Lender shortlist matched to your profile',
                        'File prepared and logged in',
                        'Valuation and legal opinion',
                        'Sanction letter reviewed with you, clause by clause',
                        'Disbursement and repayment schedule handover',
                    ],
                    'facts' => [
                        ['Security', 'Mortgage of the property'],
                        ['Tenure', 'Typically long-term; lender specific'],
                        ['Assessed on', 'Valuation and repayment capacity'],
                        ['Decision by', 'The lender, always'],
                    ],
                    'note' => 'We do not publish interest rates or processing fees. They change constantly and vary by profile — quoting a number that later moves would mislead you. Ask, and we will source the current rate card for your file.',
                    'disc' => $loanLine,
                ],
                [
                    'id' => 'home',
                    'ic' => 'i-home',
                    'title' => 'Home Loan',
                    'tag' => 'Purchase · Construction · Transfer',
                    'lead' => 'The largest borrowing most families ever do. Getting the structure right — tenure, co-applicant, part-payment discipline — matters more than chasing the last few basis points.',
                    'who' => [
                        'First-time buyers of a flat or plot',
                        'Families constructing or extending on an owned plot',
                        'Borrowers stuck on an old, higher rate who should transfer',
                        'NRIs buying in Punjab, where documentation differs',
                    ],
                    'what' => [
                        'Purchase, construction, extension and plot-plus-construction: Each has a different disbursement pattern and a different document set.',
                        'Eligibility: Income, age, existing EMIs and the lender’s FOIR limit set the amount. Adding an earning co-applicant is usually the single biggest lever.',
                        'Own contribution: Lenders fund a share of the agreement value; stamp duty and registration are generally yours to pay. Plan that cash before you book.',
                        'Fixed, floating and external benchmark: How your rate resets, and what actually happens to your EMI and tenure when the benchmark moves.',
                        'Pre-payment: On floating-rate loans to individuals, foreclosure and part-payment from own funds are generally not penalised. We show what one extra EMI a year does to your total interest.',
                        'Balance transfer: Worth doing when the rate gap covers the switching cost inside a year.',
                    ],
                    'docs' => [
                        'KYC and photographs for all applicants',
                        'Salary slips, Form 16 and 6 months salary account statements — salaried',
                        'ITR with computation and audited financials for 2–3 years — self-employed',
                        'Agreement to sell / allotment letter / builder documents',
                        'Approved plan and estimate, for construction',
                        'Existing loan statements',
                    ],
                    'steps' => [
                        'Affordability check before you commit to a property',
                        'Pre-approval so you can negotiate as a ready buyer',
                        'Full file with property papers',
                        'Technical valuation and legal vetting',
                        'Sanction, then disbursement in line with construction',
                        'Annual review of rate and pre-payment options',
                    ],
                    'facts' => [
                        ['Tenure', 'Commonly up to 20–30 years'],
                        ['Co-applicant', 'Usually increases eligibility'],
                        ['Own contribution', 'Buyer funds a share plus registration'],
                        ['Tax benefit', 'Depends on the tax regime you choose'],
                    ],
                    'note' => 'We deliberately publish no section numbers or deduction limits for home-loan tax relief. The Income-tax Act rules and deductions differ between the old and new regimes. Check your own position with a tax professional.',
                    'disc' => $loanLine,
                ],
                [
                    'id' => 'biz',
                    'ic' => 'i-brief',
                    'title' => 'Business Loan',
                    'tag' => 'Unsecured · Secured · MSME',
                    'lead' => 'Working capital, an order to fulfil, machinery to buy or a supplier to pay early. The right product depends on whether the need is one-time or revolving.',
                    'who' => [
                        'Traders and manufacturers in Ludhiana’s hosiery, cycle-parts and engineering clusters',
                        'Service businesses with receivable gaps',
                        'Proprietors and partnerships with 2–3 years of filed returns',
                        'Udyam-registered MSMEs',
                    ],
                    'what' => [
                        'Unsecured business loans: Assessed on turnover, banking conduct, bureau score and vintage. Fast, but priced for the absence of security.',
                        'Secured business loans: Property-backed, therefore cheaper and longer. Slower to complete because of legal and valuation work.',
                        'Machinery and equipment finance: The asset itself becomes the security.',
                        'Working capital: Cash credit or overdraft against stock and receivables.',
                        'Government-guaranteed routes: CGTMSE for collateral-free funding, plus current MSME schemes you may qualify for.',
                        'File quality: Most rejections come from a poorly assembled file, not a weak business. Clean banking, matching GST/ITR, zero cheque bounces.',
                    ],
                    'docs' => [
                        'KYC of proprietor / partners / directors',
                        'Udyam registration certificate',
                        'GST registration and last 12 months returns',
                        'ITR with computation and financials, 2–3 years',
                        '12 months bank statements of all current accounts',
                        'Existing loan sanction letters and repayment track',
                        'Partnership deed / MOA and AOA, where applicable',
                    ],
                    'steps' => [
                        'Understand the actual need and the repayment source',
                        'Product choice: term loan, CC/OD, or guaranteed scheme',
                        'Document checklist issued up front',
                        'File logged with the shortlisted lender',
                        'Query resolution and sanction',
                        'Post-disbursement compliance reminders',
                    ],
                    'facts' => [
                        ['Vintage usually sought', '2–3 years of filed returns'],
                        ['Key driver', 'Banking conduct and bureau score'],
                        ['Udyam registration', 'Free, and opens scheme access'],
                        ['Security', 'Depends on product and amount'],
                    ],
                    'note' => 'Under the RBI Master Direction on MSME lending dated 9 February 2026, scheduled commercial banks must not take collateral security for MSE loans up to ₹20 lakh. If a branch asks you for security below that limit, you are entitled to question it.',
                    'disc' => $loanLine,
                ],
                [
                    'id' => 'lamf',
                    'ic' => 'i-coin',
                    'title' => 'Loan Against Mutual Funds & Shares',
                    'tag' => 'Overdraft · Stay invested',
                    'lead' => 'Borrow against the portfolio you already own instead of redeeming it. Units are pledged, not sold, so your investment stays in the market and your capital gain is not triggered.',
                    'who' => [
                        'Investors facing a short-term cash need who do not want to break a long-term SIP',
                        'Business owners bridging a receivable gap',
                        'Anyone about to redeem equity funds purely for liquidity',
                    ],
                    'what' => [
                        'How the pledge works: Units are lien-marked through the registrar (CAMS/KFintech) or depositories (NSDL/CDSL). You continue to own them.',
                        'Overdraft structure: A limit is set; interest applies only on what you actually draw, for the days you draw it.',
                        'Regulatory ceilings apply from 1 July 2026 under RBI capital-market-exposure amendment directions of 13 February 2026.',
                        'Margin calls: If the market falls, the lender can ask you to pledge more or repay part of the drawing. Borrow with a safety buffer.',
                        'IPO, FPO and ESOP finance is capped at ₹25 lakh per individual with a 25 per cent cash margin.',
                    ],
                    'table' => [
                        'cap' => 'RBI ceilings applicable to banks, effective 1 July 2026',
                        'head' => ['Security pledged', 'Maximum loan-to-value', 'Overall cap'],
                        'rows' => [
                            ['Listed shares and listed convertible debt', '60%', '₹1 crore per individual, across banking system'],
                            ['Mutual funds other than debt funds, ETFs, REITs', '75%', '₹1 crore per individual, across banking system'],
                            ['Debt mutual funds', '85%', '₹1 crore per individual, across banking system'],
                            ['IPO / FPO / ESOP finance', '—', '₹25 lakh per individual, 25% cash margin'],
                        ],
                    ],
                    'docs' => [
                        'PAN and Aadhaar',
                        'Latest consolidated account statement or demat holding statement',
                        'Bank account details for the overdraft',
                        'Lien-marking request through the RTA or depository',
                    ],
                    'steps' => [
                        'Holdings reviewed and eligible securities identified',
                        'Indicative limit calculated using the LTV table',
                        'Lender application and account opening',
                        'Lien marking with CAMS / KFintech or NSDL / CDSL',
                        'Limit activated; draw only what you need',
                        'Lien released once the facility is closed',
                    ],
                    'facts' => [
                        ['Per-individual cap', '₹1 crore across banks'],
                        ['Listed shares LTV', 'Up to 60%'],
                        ['Equity MF / ETF LTV', 'Up to 75%'],
                        ['Debt MF LTV', 'Up to 85%'],
                    ],
                    'note' => 'A falling market reduces the value of your pledged security. The lender can then demand additional security or partial repayment at short notice. Borrow well inside the limit, not at it.',
                    'disc' => $loanLine,
                ],
                [
                    'id' => 'ccod',
                    'ic' => 'i-refresh',
                    'title' => 'Cash Credit & Overdraft',
                    'tag' => 'Working capital limits',
                    'lead' => 'A revolving limit against stock and book debts. You draw when you need it, repay when collections arrive, and pay interest only on the daily outstanding.',
                    'who' => [
                        'Traders and manufacturers carrying inventory',
                        'Businesses with 60–90 day receivable cycles',
                        'Firms currently funding working capital with a costly term loan',
                    ],
                    'what' => [
                        'Drawing power: Calculated monthly from your stock and debtors statement, less creditors, with the lender’s margin applied.',
                        'Cash credit versus overdraft: CC is secured by current assets; OD may be against property, deposits or securities.',
                        'Stock statements and audits: Monthly statements, periodic stock audits and annual renewal of the limit.',
                        'Interest costs only what you use: Discipline in routing collections through the account directly reduces your interest bill.',
                    ],
                    'docs' => [
                        'GST returns for the last 12 months',
                        'Audited financials for 2–3 years',
                        'Provisional financials for the current year',
                        'Stock and debtors statement',
                        'Existing sanction letters and conduct of accounts',
                        'Security documents — property or deposits',
                    ],
                    'steps' => [
                        'Working capital cycle assessed in days',
                        'Limit requirement computed honestly',
                        'Proposal prepared with projections',
                        'Lender assessment and sanction',
                        'Documentation, charge creation and activation',
                    ],
                    'facts' => [
                        ['Interest on', 'Daily outstanding, not the full limit'],
                        ['Renewal', 'Annually, with fresh financials'],
                        ['Drawing power', 'Reviewed monthly'],
                        ['Security', 'Current assets, often plus collateral'],
                    ],
                    'note' => 'Route your collections through the CC account rather than a separate current account. It lowers your interest cost and builds the banking conduct record that decides your next enhancement.',
                    'disc' => $loanLine,
                ],
                [
                    'id' => 'cgtmse',
                    'ic' => 'i-shield',
                    'title' => 'Collateral-Free Loan (CGTMSE)',
                    'tag' => 'Credit Guarantee Fund Trust',
                    'lead' => 'The Credit Guarantee Fund Trust for Micro and Small Enterprises lets a lender advance credit without collateral or a third-party guarantee, because the Trust guarantees a large share of the exposure.',
                    'who' => [
                        'New and existing micro and small enterprises',
                        'Manufacturers and service units with no property to pledge',
                        'Women-led enterprises, who receive enhanced cover',
                        'Udyam-registered units seeking their first institutional facility',
                    ],
                    'what' => [
                        'The guarantee is taken by the lender, not by you. You cannot apply to CGTMSE directly. Your bank obtains the cover.',
                        'Ceiling of ₹10 crore per borrower since 1 April 2025.',
                        'Guarantee cover is commonly in the 75–85 per cent range (enhanced for women-led units).',
                        'Annual Guarantee Fee is charged on the guaranteed amount at slab rates.',
                        'Under RBI’s MSME Master Direction of 9 February 2026, scheduled commercial banks must not take collateral for MSE loans up to ₹20 lakh.',
                    ],
                    'table' => [
                        'cap' => 'Annual Guarantee Fee (Standard Rates, effective 1 April 2025)',
                        'head' => ['Credit facility', 'Standard AGF (per annum)'],
                        'rows' => [
                            ['Up to ₹10 lakh', '0.37%'],
                            ['Above ₹10 lakh and up to ₹50 lakh', '0.55%'],
                            ['Above ₹50 lakh and up to ₹1 crore', '0.60%'],
                            ['Above ₹1 crore and up to ₹2 crore', '0.85%'],
                            ['Above ₹2 crore and up to ₹5 crore', '1.00%'],
                            ['Above ₹5 crore and up to ₹8 crore', '1.10%'],
                            ['Above ₹8 crore and up to ₹10 crore', '1.20%'],
                        ],
                    ],
                    'docs' => [
                        'Udyam registration certificate',
                        'KYC of the proprietor, partners or directors',
                        'Project report with cost and means of finance',
                        'ITR and financials where the unit is existing',
                        'Bank statements, 12 months',
                        'Quotations for machinery or equipment',
                    ],
                    'steps' => [
                        'Eligibility checked against scheme conditions',
                        'Project report prepared to lender standard',
                        'Application logged with an eligible lending institution',
                        'Lender appraisal and sanction',
                        'Lender obtains CGTMSE cover for the facility',
                        'Disbursement and ongoing compliance',
                    ],
                    'facts' => [
                        ['Guarantee ceiling', '₹10 crore per borrower'],
                        ['Cover', '75–85%; higher for women-led units'],
                        ['Who applies', 'The lending institution'],
                        ['Collateral-free to ₹20 lakh', 'RBI rule for MSE loans at banks'],
                    ],
                    'note' => 'A CGTMSE guarantee protects the lender against default. It does not forgive your liability. You remain fully responsible for repayment.',
                    'disc' => $loanLine,
                ],
            ],
        ];
    }
}
