<?php

namespace App\Domain\Calculators\Services;

class CalculatorCatalogService
{
    public static function getData(): array
    {
        $illus = 'Illustrative only. Not a guarantee of returns, an offer, a quotation or advice.';
        $mfRisk = 'Mutual Fund investments are subject to market risks, read all scheme related documents carefully.';
        $insLine = 'Insurance is the subject matter of solicitation.';

        return [
            'calculators' => [
                [
                    'id' => 'sip',
                    'ic' => 'i-growth',
                    'label' => 'SIP',
                    'title' => 'SIP Calculator',
                    'desc' => 'What a fixed monthly investment could grow to, at a rate of return you choose.',
                    'fields' => [
                        ['k' => 'p', 'l' => 'Monthly investment', 't' => 'range', 'min' => 500, 'max' => 200000, 'step' => 500, 'def' => 10000, 'fmt' => 'inr'],
                        ['k' => 'y', 'l' => 'Investment period', 't' => 'range', 'min' => 1, 'max' => 40, 'step' => 1, 'def' => 15, 'fmt' => 'yr'],
                        ['k' => 'r', 'l' => 'Assumed annual return', 't' => 'range', 'min' => 1, 'max' => 20, 'step' => 0.5, 'def' => 11, 'fmt' => 'pct'],
                    ],
                    'assume' => 'Assumes the instalment is invested at the start of every month and that the return is earned evenly. Real returns vary year to year and can be negative.',
                    'disc' => "$illus $mfRisk",
                ],
                [
                    'id' => 'lump',
                    'ic' => 'i-coin',
                    'label' => 'Lump sum',
                    'title' => 'Lump Sum Calculator',
                    'desc' => 'What a one-time investment could become over time.',
                    'fields' => [
                        ['k' => 'p', 'l' => 'Amount invested', 't' => 'range', 'min' => 10000, 'max' => 20000000, 'step' => 10000, 'def' => 500000, 'fmt' => 'inr'],
                        ['k' => 'y', 'l' => 'Investment period', 't' => 'range', 'min' => 1, 'max' => 40, 'step' => 1, 'def' => 10, 'fmt' => 'yr'],
                        ['k' => 'r', 'l' => 'Assumed annual return', 't' => 'range', 'min' => 1, 'max' => 20, 'step' => 0.5, 'def' => 11, 'fmt' => 'pct'],
                    ],
                    'assume' => 'Compounded annually at the rate you enter. Charges and tax are not deducted.',
                    'disc' => "$illus $mfRisk",
                ],
                [
                    'id' => 'stepup',
                    'ic' => 'i-growth',
                    'label' => 'Step-up SIP',
                    'title' => 'Step-up SIP Calculator',
                    'desc' => 'Increase your SIP by a fixed percentage every year, as your income grows.',
                    'fields' => [
                        ['k' => 'p', 'l' => 'Starting monthly investment', 't' => 'range', 'min' => 500, 'max' => 200000, 'step' => 500, 'def' => 10000, 'fmt' => 'inr'],
                        ['k' => 's', 'l' => 'Annual step-up', 't' => 'range', 'min' => 0, 'max' => 25, 'step' => 1, 'def' => 10, 'fmt' => 'pct'],
                        ['k' => 'y', 'l' => 'Investment period', 't' => 'range', 'min' => 1, 'max' => 40, 'step' => 1, 'def' => 15, 'fmt' => 'yr'],
                        ['k' => 'r', 'l' => 'Assumed annual return', 't' => 'range', 'min' => 1, 'max' => 20, 'step' => 0.5, 'def' => 11, 'fmt' => 'pct'],
                    ],
                    'assume' => 'The instalment rises on each anniversary. Charges and tax are not deducted.',
                    'disc' => "$illus $mfRisk",
                ],
                [
                    'id' => 'swp',
                    'ic' => 'i-refresh',
                    'label' => 'SWP',
                    'title' => 'Withdrawal Plan (SWP)',
                    'desc' => 'Draw a monthly income from a corpus and see how long it lasts.',
                    'fields' => [
                        ['k' => 'c', 'l' => 'Corpus available', 't' => 'range', 'min' => 100000, 'max' => 50000000, 'step' => 50000, 'def' => 5000000, 'fmt' => 'inr'],
                        ['k' => 'w', 'l' => 'Monthly withdrawal', 't' => 'range', 'min' => 1000, 'max' => 500000, 'step' => 1000, 'def' => 30000, 'fmt' => 'inr'],
                        ['k' => 'r', 'l' => 'Assumed annual return', 't' => 'range', 'min' => 1, 'max' => 15, 'step' => 0.5, 'def' => 8, 'fmt' => 'pct'],
                        ['k' => 'y', 'l' => 'Check over', 't' => 'range', 'min' => 5, 'max' => 40, 'step' => 1, 'def' => 25, 'fmt' => 'yr'],
                    ],
                    'assume' => 'Withdrawal is taken at the end of each month. Steady returns assumed.',
                    'disc' => "$illus $mfRisk",
                ],
                [
                    'id' => 'goal',
                    'ic' => 'i-target',
                    'label' => 'Goal planner',
                    'title' => 'Goal Planner',
                    'desc' => 'What a goal will cost when you reach it, and what you must save each month to get there.',
                    'fields' => [
                        ['k' => 'g', 'l' => 'Cost of the goal today', 't' => 'range', 'min' => 50000, 'max' => 50000000, 'step' => 50000, 'def' => 2500000, 'fmt' => 'inr'],
                        ['k' => 'y', 'l' => 'Years to the goal', 't' => 'range', 'min' => 1, 'max' => 35, 'step' => 1, 'def' => 12, 'fmt' => 'yr'],
                        ['k' => 'f', 'l' => 'Assumed inflation', 't' => 'range', 'min' => 0, 'max' => 12, 'step' => 0.5, 'def' => 6, 'fmt' => 'pct'],
                        ['k' => 'r', 'l' => 'Assumed annual return', 't' => 'range', 'min' => 1, 'max' => 20, 'step' => 0.5, 'def' => 11, 'fmt' => 'pct'],
                        ['k' => 'e', 'l' => 'Already saved for this goal', 't' => 'range', 'min' => 0, 'max' => 20000000, 'step' => 25000, 'def' => 0, 'fmt' => 'inr'],
                    ],
                    'assume' => 'The goal cost is inflated to target date, then existing savings are grown at the assumed return.',
                    'disc' => "$illus $mfRisk",
                ],
                [
                    'id' => 'retire',
                    'ic' => 'i-clock',
                    'label' => 'Retirement',
                    'title' => 'Retirement Planner',
                    'desc' => 'The corpus you need at retirement, and the monthly saving that builds it.',
                    'fields' => [
                        ['k' => 'a', 'l' => 'Your age now', 't' => 'range', 'min' => 20, 'max' => 60, 'step' => 1, 'def' => 35, 'fmt' => 'num', 'unit' => ' yrs'],
                        ['k' => 'ra', 'l' => 'Retirement age', 't' => 'range', 'min' => 40, 'max' => 70, 'step' => 1, 'def' => 60, 'fmt' => 'num', 'unit' => ' yrs'],
                        ['k' => 'le', 'l' => 'Plan until age', 't' => 'range', 'min' => 65, 'max' => 100, 'step' => 1, 'def' => 85, 'fmt' => 'num', 'unit' => ' yrs'],
                        ['k' => 'e', 'l' => 'Monthly expenses today', 't' => 'range', 'min' => 10000, 'max' => 500000, 'step' => 5000, 'def' => 50000, 'fmt' => 'inr'],
                        ['k' => 'f', 'l' => 'Assumed inflation', 't' => 'range', 'min' => 2, 'max' => 12, 'step' => 0.5, 'def' => 6, 'fmt' => 'pct'],
                        ['k' => 'r1', 'l' => 'Return before retirement', 't' => 'range', 'min' => 2, 'max' => 18, 'step' => 0.5, 'def' => 11, 'fmt' => 'pct'],
                        ['k' => 'r2', 'l' => 'Return after retirement', 't' => 'range', 'min' => 1, 'max' => 12, 'step' => 0.5, 'def' => 7, 'fmt' => 'pct'],
                        ['k' => 's', 'l' => 'Retirement savings so far', 't' => 'range', 'min' => 0, 'max' => 50000000, 'step' => 100000, 'def' => 500000, 'fmt' => 'inr'],
                    ],
                    'assume' => 'Expenses are inflated to retirement date and withdrawn monthly, growing with inflation.',
                    'disc' => "$illus $mfRisk",
                ],
                [
                    'id' => 'emi',
                    'ic' => 'i-calc',
                    'label' => 'EMI',
                    'title' => 'Loan EMI Calculator',
                    'desc' => 'Your monthly instalment, total interest, and what the loan really costs.',
                    'fields' => [
                        ['k' => 'p', 'l' => 'Loan amount', 't' => 'range', 'min' => 50000, 'max' => 50000000, 'step' => 50000, 'def' => 3000000, 'fmt' => 'inr'],
                        ['k' => 'r', 'l' => 'Interest rate', 't' => 'range', 'min' => 5, 'max' => 24, 'step' => 0.05, 'def' => 9, 'fmt' => 'pct'],
                        ['k' => 'y', 'l' => 'Tenure', 't' => 'range', 'min' => 1, 'max' => 30, 'step' => 1, 'def' => 20, 'fmt' => 'yr'],
                        ['k' => 'x', 'l' => 'Extra payment each month', 't' => 'range', 'min' => 0, 'max' => 100000, 'step' => 500, 'def' => 0, 'fmt' => 'inr'],
                    ],
                    'assume' => 'Reducing-balance interest at a constant rate. Extra payment treated as additional principal reduction.',
                    'disc' => "$illus Actual EMI, rate and charges are set by the lender.",
                ],
                [
                    'id' => 'elig',
                    'ic' => 'i-bank',
                    'label' => 'Loan eligibility',
                    'title' => 'Loan Eligibility (Indicative)',
                    'desc' => 'A FOIR-based estimate of how much a lender might consider.',
                    'fields' => [
                        ['k' => 'i', 'l' => 'Net monthly income', 't' => 'range', 'min' => 15000, 'max' => 2000000, 'step' => 5000, 'def' => 100000, 'fmt' => 'inr'],
                        ['k' => 'o', 'l' => 'Existing EMIs per month', 't' => 'range', 'min' => 0, 'max' => 500000, 'step' => 1000, 'def' => 15000, 'fmt' => 'inr'],
                        ['k' => 'foir', 'l' => 'FOIR the lender allows', 't' => 'range', 'min' => 30, 'max' => 75, 'step' => 1, 'def' => 55, 'fmt' => 'pct'],
                        ['k' => 'r', 'l' => 'Interest rate', 't' => 'range', 'min' => 5, 'max' => 24, 'step' => 0.05, 'def' => 9, 'fmt' => 'pct'],
                        ['k' => 'y', 'l' => 'Tenure', 't' => 'range', 'min' => 1, 'max' => 30, 'step' => 1, 'def' => 20, 'fmt' => 'yr'],
                    ],
                    'assume' => 'FOIR is the share of income a lender lets you commit to all EMIs together.',
                    'disc' => 'This is not a loan approval or sanction. Eligibility is decided solely by the lender.',
                ],
                [
                    'id' => 'lamf',
                    'ic' => 'i-coin',
                    'label' => 'Loan vs securities',
                    'title' => 'Loan Against Securities (Indicative)',
                    'desc' => 'An indicative limit against your holdings, using the RBI ceilings effective 1 July 2026.',
                    'fields' => [
                        ['k' => 'sh', 'l' => 'Value of listed shares', 't' => 'range', 'min' => 0, 'max' => 50000000, 'step' => 50000, 'def' => 1000000, 'fmt' => 'inr'],
                        ['k' => 'eq', 'l' => 'Equity funds, ETFs, REITs', 't' => 'range', 'min' => 0, 'max' => 50000000, 'step' => 50000, 'def' => 2000000, 'fmt' => 'inr'],
                        ['k' => 'db', 'l' => 'Debt mutual funds', 't' => 'range', 'min' => 0, 'max' => 50000000, 'step' => 50000, 'def' => 500000, 'fmt' => 'inr'],
                    ],
                    'assume' => 'Applies RBI ceilings: 60% on listed shares, 75% on equity funds/ETFs, 85% on debt funds, capped at ₹1 crore per individual across banks.',
                    'disc' => 'Indicative only. The lender decides the eligible securities and final limit.',
                ],
                [
                    'id' => 'hlv',
                    'ic' => 'i-family',
                    'label' => 'Life cover',
                    'title' => 'Life Cover Need (HLV)',
                    'desc' => 'How much life cover your household would actually need if your income stopped.',
                    'fields' => [
                        ['k' => 'inc', 'l' => 'Your annual income', 't' => 'range', 'min' => 100000, 'max' => 50000000, 'step' => 50000, 'def' => 1200000, 'fmt' => 'inr'],
                        ['k' => 'yrs', 'l' => 'Years the family needs support', 't' => 'range', 'min' => 5, 'max' => 40, 'step' => 1, 'def' => 20, 'fmt' => 'yr'],
                        ['k' => 'deb', 'l' => 'Loans outstanding', 't' => 'range', 'min' => 0, 'max' => 50000000, 'step' => 50000, 'def' => 2500000, 'fmt' => 'inr'],
                        ['k' => 'goal', 'l' => 'Future goals to fund', 't' => 'range', 'min' => 0, 'max' => 50000000, 'step' => 50000, 'def' => 2000000, 'fmt' => 'inr'],
                        ['k' => 'ass', 'l' => 'Existing savings and investments', 't' => 'range', 'min' => 0, 'max' => 50000000, 'step' => 50000, 'def' => 1000000, 'fmt' => 'inr'],
                        ['k' => 'cov', 'l' => 'Life cover you already hold', 't' => 'range', 'min' => 0, 'max' => 100000000, 'step' => 100000, 'def' => 1000000, 'fmt' => 'inr'],
                    ],
                    'assume' => 'Income replacement discounted at real rate of 3% per year.',
                    'disc' => "$illus $insLine",
                ],
                [
                    'id' => 'health',
                    'ic' => 'i-heart',
                    'label' => 'Health cover',
                    'title' => 'Health Cover Adequacy',
                    'desc' => 'A starting sum insured for your family, and whether a top-up makes more sense.',
                    'fields' => [
                        ['k' => 'city', 'l' => 'Where you would be treated', 't' => 'sel', 'def' => 'tier2', 'opts' => [['metro', 'Metro — Delhi, Mumbai, Bengaluru'], ['tier2', 'Large city — Ludhiana, Jalandhar, Chandigarh'], ['tier3', 'Smaller town']]],
                        ['k' => 'adults', 'l' => 'Adults to cover', 't' => 'range', 'min' => 1, 'max' => 4, 'step' => 1, 'def' => 2, 'fmt' => 'num'],
                        ['k' => 'kids', 'l' => 'Children to cover', 't' => 'range', 'min' => 0, 'max' => 4, 'step' => 1, 'def' => 2, 'fmt' => 'num'],
                        ['k' => 'age', 'l' => 'Age of the eldest member', 't' => 'range', 'min' => 18, 'max' => 85, 'step' => 1, 'def' => 42, 'fmt' => 'num', 'unit' => ' yrs'],
                        ['k' => 'ped', 'l' => 'Any diagnosed condition in the family', 't' => 'sel', 'def' => 'no', 'opts' => [['no', 'No'], ['yes', 'Yes — diabetes, hypertension, etc.']]],
                        ['k' => 'cur', 'l' => 'Cover you hold today', 't' => 'range', 'min' => 0, 'max' => 10000000, 'step' => 50000, 'def' => 500000, 'fmt' => 'inr'],
                    ],
                    'assume' => 'Built from typical hospital costs by city tier, family size and member age.',
                    'disc' => "Guidance only. $insLine",
                ],
                [
                    'id' => 'idv',
                    'ic' => 'i-car',
                    'label' => 'Motor IDV',
                    'title' => 'Motor IDV & NCB',
                    'desc' => 'A rough IDV from vehicle age, and the NCB you should be getting.',
                    'fields' => [
                        ['k' => 'price', 'l' => 'Ex-showroom price when new', 't' => 'range', 'min' => 50000, 'max' => 10000000, 'step' => 10000, 'def' => 900000, 'fmt' => 'inr'],
                        ['k' => 'age', 'l' => 'Age of the vehicle', 't' => 'sel', 'def' => '2', 'opts' => [['0', 'Under 6 months'], ['0.5', '6 months to 1 year'], ['1', '1 to 2 years'], ['2', '2 to 3 years'], ['3', '3 to 4 years'], ['4', '4 to 5 years'], ['5', 'Over 5 years']]],
                        ['k' => 'acc', 'l' => 'Value of fitted accessories', 't' => 'range', 'min' => 0, 'max' => 500000, 'step' => 5000, 'def' => 0, 'fmt' => 'inr'],
                        ['k' => 'ncb', 'l' => 'Consecutive claim-free years', 't' => 'sel', 'def' => '2', 'opts' => [['0', 'None — claimed last year'], ['1', '1 year'], ['2', '2 years'], ['3', '3 years'], ['4', '4 years'], ['5', '5 years or more']]],
                    ],
                    'assume' => 'Uses standard depreciation schedule for own-damage cover up to 5 years.',
                    'disc' => 'Indicative only. The insurer sets the final IDV and NCB.',
                ],
                [
                    'id' => 'cgtmse',
                    'ic' => 'i-shield',
                    'label' => 'CGTMSE check',
                    'title' => 'CGTMSE Eligibility Check',
                    'desc' => 'A quick self-check against the scheme conditions, with indicative guarantee fee.',
                    'fields' => [
                        ['k' => 'amt', 'l' => 'Credit facility required', 't' => 'range', 'min' => 100000, 'max' => 100000000, 'step' => 100000, 'def' => 3000000, 'fmt' => 'inr'],
                        ['k' => 'udyam', 'l' => 'Udyam registered as MSE', 't' => 'chk', 'def' => 1],
                        ['k' => 'type', 'l' => 'Manufacturing, service or eligible trading', 't' => 'chk', 'def' => 1],
                        ['k' => 'nocol', 'l' => 'No collateral offered', 't' => 'chk', 'def' => 1],
                        ['k' => 'lender', 'l' => 'Applying through bank/eligible institution', 't' => 'chk', 'def' => 1],
                        ['k' => 'clean', 'l' => 'Clean repayment track, no wilful default', 't' => 'chk', 'def' => 1],
                        ['k' => 'women', 'l' => 'Women-led enterprise', 't' => 'chk', 'def' => 0],
                    ],
                    'assume' => 'Checks headline scheme conditions and applies standard Annual Guarantee Fee slabs.',
                    'disc' => 'This is not an approval. The lending institution applies for the guarantee.',
                ],
                [
                    'id' => 'risk',
                    'ic' => 'i-scale',
                    'label' => 'Risk comfort',
                    'title' => 'Risk Comfort Check',
                    'desc' => 'Five questions about you, not about markets. The answer shapes your strategy.',
                    'fields' => [
                        ['k' => 'age', 'l' => 'Your age', 't' => 'sel', 'def' => '4', 'opts' => [['5', 'Under 30'], ['4', '30 to 40'], ['3', '40 to 50'], ['2', '50 to 60'], ['1', 'Over 60']]],
                        ['k' => 'hz', 'l' => 'When will you need this money?', 't' => 'sel', 'def' => '4', 'opts' => [['1', 'Within 3 years'], ['2', '3 to 5 years'], ['4', '5 to 10 years'], ['5', 'More than 10 years']]],
                        ['k' => 'drop', 'l' => 'Your portfolio falls 20% in a month. You…', 't' => 'sel', 'def' => '4', 'opts' => [['1', 'Sell everything and step away'], ['2', 'Sell some to stop the bleeding'], ['4', 'Do nothing and wait it out'], ['5', 'Invest more while it is cheaper']]],
                        ['k' => 'inc', 'l' => 'How steady is your income?', 't' => 'sel', 'def' => '4', 'opts' => [['1', 'Irregular or seasonal'], ['2', 'Steady but fully committed'], ['4', 'Steady with a monthly surplus'], ['5', 'More than one reliable source']]],
                        ['k' => 'exp', 'l' => 'What have you invested in before?', 't' => 'sel', 'def' => '2', 'opts' => [['1', 'Only FDs, savings or gold'], ['2', 'Some mutual funds'], ['4', 'Mutual funds for several years'], ['5', 'Direct equity, actively']]],
                    ],
                    'assume' => 'Five-factor scoring: capacity to take risk weighed against willingness to take it.',
                    'disc' => "Educational and indicative only. $mfRisk",
                ],
            ],
        ];
    }
}
